import json
import os
import glob
from tqdm import tqdm

def check_bbox_coverage(list_file, root_dir, bbox_file):
    print(f"Checking BBOX coverage for {list_file} against {bbox_file}...")
    
    with open(bbox_file, 'r') as f:
        boxs = json.load(f)
        
    total_videos = 0
    total_frames_expected = 0
    hit_exact = 0
    hit_fallback = 0
    missed = 0
    
    with open(list_file, 'r') as f:
        lines = f.readlines()
        
    for line in tqdm(lines, desc="Analyzing"):
        parts = line.strip().split(' ')
        if len(parts) > 3:
            path = ' '.join(parts[:-2])
            num_frames = int(parts[-2])
            label = int(parts[-1])
        else:
            path = parts[0]
            num_frames = int(parts[1])
            label = int(parts[2])
            
        # Optional: You can filter by label here if needed (e.g., only check first 7 classes)
        # However, the list file generated by CAER loader already maps to 1-7.
            
        total_videos += 1
        total_frames_expected += num_frames
        
        # Match logic from dataloader
        rel_path = path.replace('./', '').replace('\\', '/')
        video_key_full = os.path.splitext(rel_path)[0]
        
        matched_video_key = None
        if video_key_full in boxs:
            matched_video_key = video_key_full
        else:
            parts = video_key_full.split('/')
            for idx in range(1, len(parts)):
                sub_key = '/'.join(parts[idx:])
                if sub_key in boxs:
                    matched_video_key = sub_key
                    break
                    
        if matched_video_key:
            # Check all frames (simulating sampling)
            for p in range(num_frames):
                frame_key_exact = f"{p}.jpg"
                
                if frame_key_exact in boxs[matched_video_key]:
                    hit_exact += 1
                else:
                    # Try fallbacks
                    found_fallback = False
                    for fk in [f"{p-1}.jpg", f"{p+1}.jpg", f"{p-2}.jpg", f"{p+2}.jpg", f"{p:06d}.jpg", f"{p+1:06d}.jpg", f"{p-1:06d}.jpg"]:
                        if fk in boxs[matched_video_key]:
                            hit_fallback += 1
                            found_fallback = True
                            break
                    if not found_fallback:
                        missed += 1
        else:
            missed += num_frames
            
    print("\n--- BBOX COVERAGE REPORT ---")
    print(f"Total Videos: {total_videos}")
    print(f"Total Frames Checked: {total_frames_expected}")
    print(f"Exact Match ('p.jpg'): {hit_exact} ({(hit_exact/total_frames_expected)*100:.2f}%)")
    print(f"Fallback Match (nearby/zero-padded): {hit_fallback} ({(hit_fallback/total_frames_expected)*100:.2f}%)")
    print(f"TOTAL HIT: {hit_exact + hit_fallback} ({((hit_exact + hit_fallback)/total_frames_expected)*100:.2f}%)")
    print(f"MISSED (Needs Haar/CenterCrop): {missed} ({(missed/total_frames_expected)*100:.2f}%)")

if __name__ == '__main__':
    check_bbox_coverage(
        list_file='./CAER_Video/train.txt',
        root_dir='./CAER_Video',
        bbox_file='./CAER_Video/face_boxes_mediapipe.json'
    )
